from deck_layout.handler_bed import DEFAULT_SYRINGE_FLOWRATE

MIXING_RATE = 2 * DEFAULT_SYRINGE_FLOWRATE
MIN_PIPETTE_VOLUME = 10.0
NEW_VIAL_VOLUME = 250.0
MAX_VIAL_VOLUME = 1_000.0
MAX_MOVE_VOLUME = 900.0
BACK_AIR_GAP = 20.0
FRONT_AIR_GAP = 10.0
